### ISSUE TITLE
Payload exceeded size when using wailia

### ISSUE THREAD

**Issue by mdinnocenzo** [NinjaPhenix/FabricMods#81] opened 2020-11-26 04:05 UTC
Expanded storage is passing a payload larger than 1gb to wailia.  I was able to remedy this by removing the inventory display of wailia.

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[20:41:24] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
        at net.minecraft.class_2658.<init>(class_2658.java:43) ~[intermediary-server.jar:?]
        at mcp.mobius.waila.network.NetworkHandler.lambda$null$8(NetworkHandler.java:87) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]

**Comment by NinjaPhenix** [comment] 2020-11-26 14:57
Expanded Storage has no integration with "wailia", so I can only assume this is an issue with Hwyla.

**Comment by deirn** [comment] 2020-12-19 13:07
it's probably [megane](https://github.com/badasintended/megane), i just released a version that fixed this issue so you can close this

**Comment by NinjaPhenix** [comment] 2020-12-19 15:30
Closing as this issue is fixed by deirn and well It's not a problem directly caused by Expanded Storage.

**Closed by NinjaPhenix** 2020-12-19 15:30 UTC
