### ISSUE TITLE
Hoppers aren't recognizing expanded chest capacity 

### ISSUE THREAD

**Issue by Cancleout** [NinjaPhenix/FabricMods#63] opened 2020-08-25 23:52 UTC
hoppers stop feeding chests when the first 54 slots are full

**Comment by Cancleout** [comment] 2020-08-26 05:53
follow up: it looks to only be having the issue with prismarine shards and crystals

**Comment by NinjaPhenix** [comment] 2020-08-26 09:25
Tested with only expanded storage and it works fine for me, If its limited to those two items I'd expect its a mod compatibility issue but I wouldn't know where to begin without a list of mods you were using.

**Comment by Cancleout** [comment] 2020-08-26 18:28
thanks for checking, ill try and figure out what mod is causing the problem and let you know

**Comment by Cancleout** [comment] 2020-08-26 21:45
ok.  I have pulled  every mod out, one by one, until all i have left was 
expanded storage  5.5.22
fabric api 0.19.0 build .398

im am using fabric build  0.9.2+build.206

hoppers are still seeing only the chest the are touching, and not the other half of a double chest

![image](https://user-images.githubusercontent.com/10332712/91360114-740b0000-e7bb-11ea-9c3d-3d596bd9e40f.png)

![image](https://user-images.githubusercontent.com/10332712/91360076-5f2e6c80-e7bb-11ea-9e85-985db957ac35.png)

**Comment by NinjaPhenix** [comment] 2020-08-26 21:50
Sorry I misunderstood your original issue and didn't check double chests.

The fact that hoppers stop inserting when the first chest of a double chest is full is a bug and I'll be looking into fixing it tomorrow. Sorry for the extra work you have done on your part.

**Comment by NinjaPhenix** [comment] 2020-08-26 21:52
As a side note, I'm pretty sure the root cause of this issue and #62 are the same.

**Comment by Cancleout** [comment] 2020-08-26 21:58
In fairness to you, I failed to mention double chests.

**Comment by NinjaPhenix** [comment] 2020-08-26 22:59
Fixed in 27fe7d0645a8564588ced0b50e09d961592239e6, pending release ( likely ~12 hours as I would like to get other issues closed as well. )

**Comment by Cancleout** [comment] 2020-08-26 23:09
thanks for your quick work

**Comment by NinjaPhenix** [comment] 2020-08-27 11:19
Fixed in https://www.curseforge.com/minecraft/mc-mods/expanded-storage-fabric/files/3043410

**Closed by NinjaPhenix** 2020-08-27 11:19 UTC
Labels: expandedstorage, fixed
